


CUDA_VISIBLE_DEVICES=2 /home/datdb/anaconda3/bin/python3 -u /local/datdb/ICD9multitask/multitask_model/multitask.py --not_train_w2v_emb --epoch 200 --do_label_label --lr .001 --lr_optim_y .01 --lr_predict_y .0001 --epoch_predict_y 200 --L2_scale 1 --result_folder m3icd6SmallFixW2vUpCnnMid12SgdFree --num_of_filter 50 --label_encoded_dim 50 --w2v_emb 100 --batch_size 16 --init_label_emb --label_layer_dim 12 --epoch_y 50 --epoch_params 5 --model_cnn /local/datdb/MIMIC3database/format10Jan2019/m3icdManualSmall6FixW2v/current_best.pytorch --add_name _manual_small_6icd --weight_term 1 --top_k 2 --warm_start --near_cnn 0 > /local/datdb/ICD9multitask/multitask_model/m3icd6SmallFixW2vUpCnnMid12SgdFree.txt


CUDA_VISIBLE_DEVICES=3 /home/datdb/anaconda3/bin/python3 -u /local/datdb/ICD9multitask/multitask_model/multitask.py --not_train_w2v_emb --epoch 200 --do_label_label --lr .0001 --lr_optim_y .01 --lr_predict_y .001 --epoch_predict_y 200 --L2_scale 1 --result_folder m3icd6SmallFixW2vUpCnnMid12SgdCon --num_of_filter 50 --label_encoded_dim 50 --w2v_emb 100 --batch_size 16 --init_label_emb --label_layer_dim 12 --epoch_y 25 --epoch_params 10 --model_cnn /local/datdb/MIMIC3database/format10Jan2019/m3icdManualSmall6FixW2v/current_best.pytorch --add_name _manual_small_6icd --weight_term 1 --top_k 2 --warm_start --near_cnn 0 --do_constraint > /local/datdb/ICD9multitask/multitask_model/m3icd6SmallFixW2vUpCnnMid12SgdCon.txt

CUDA_VISIBLE_DEVICES=1 /home/datdb/anaconda3/bin/python3 -u /local/datdb/ICD9multitask/multitask_model/multitask.py --not_train_w2v_emb --epoch 200 --do_label_label --lr .0001 --lr_optim_y .01 --lr_predict_y .001 --epoch_predict_y 200 --L2_scale 1 --result_folder m3icd6SmallFixW2vUpCnnMid6SgdCon --num_of_filter 50 --label_encoded_dim 50 --w2v_emb 100 --batch_size 16 --init_label_emb --label_layer_dim 6 --epoch_y 25 --epoch_params 10 --model_cnn /local/datdb/MIMIC3database/format10Jan2019/m3icdManualSmall6FixW2v/current_best.pytorch --add_name _manual_small_6icd --weight_term 1 --top_k 2 --warm_start --near_cnn 0 --do_constraint > /local/datdb/ICD9multitask/multitask_model/m3icd6SmallFixW2vUpCnnMid6SgdCon.txt

CUDA_VISIBLE_DEVICES=1 /home/datdb/anaconda3/bin/python3 -u /local/datdb/ICD9multitask/multitask_model/multitask.py --not_train_w2v_emb --epoch 1 --do_label_label --lr .0001 --lr_optim_y .01 --lr_predict_y .001 --epoch_predict_y 200 --L2_scale 1 --result_folder m3icd6SmallFixW2vUpCnnMid6SgdCon --num_of_filter 50 --label_encoded_dim 50 --w2v_emb 100 --batch_size 16 --init_label_emb --label_layer_dim 6 --epoch_y 25 --epoch_params 10 --model_cnn /local/datdb/MIMIC3database/format10Jan2019/m3icdManualSmall6FixW2v/current_best.pytorch --model_load /local/datdb/MIMIC3database/format10Jan2019/m3icd6SmallFixW2vUpCnnMid6SgdCon/current_best.pytorch --add_name _manual_small_6icd --weight_term 1 --top_k 2 --warm_start --near_cnn 0 --do_constraint --do_test > /local/datdb/ICD9multitask/multitask_model/m3icd6SmallFixW2vUpCnnMid6SgdConSortTie.txt


CUDA_VISIBLE_DEVICES=2 /home/datdb/anaconda3/bin/python3 -u /local/datdb/ICD9multitask/multitask_model/multitask.py --not_train_w2v_emb --epoch 200 --do_label_label --lr .001 --lr_optim_y .01 --lr_predict_y .0001 --epoch_predict_y 200 --L2_scale 1 --result_folder m3icd6SmallFixW2vUpCnnMid6SgdFree --num_of_filter 50 --label_encoded_dim 50 --w2v_emb 100 --batch_size 16 --init_label_emb --label_layer_dim 12 --epoch_y 50 --epoch_params 5 --model_cnn /local/datdb/MIMIC3database/format10Jan2019/m3icdManualSmall6FixW2v/current_best.pytorch --model_load /local/datdb/MIMIC3database/format10Jan2019/m3icd6SmallFixW2vUpCnnMid6SgdFree/current_best.pytorch --add_name _manual_small_6icd --weight_term 1 --top_k 2 --warm_start --near_cnn 0 --do_test > /local/datdb/ICD9multitask/multitask_model/m3icd6SmallFixW2vUpCnnMid6SgdFreeSortTie.txt


## turn off label ... constraint sgd will be same as standard sgd 

CUDA_VISIBLE_DEVICES=4 /home/datdb/anaconda3/bin/python3 -u /local/datdb/ICD9multitask/multitask_model/multitask.py --not_train_w2v_emb --epoch 200 --lr .00001 --lr_optim_y .001 --lr_predict_y .0001 --epoch_predict_y 200 --L2_scale 1 --result_folder m3icd6SmallFixW2vUpCnnMid6SgdFreeLabOff --num_of_filter 50 --label_encoded_dim 50 --w2v_emb 100 --batch_size 16 --init_label_emb --label_layer_dim 6 --epoch_y 100 --epoch_params 25 --model_cnn /local/datdb/MIMIC3database/format10Jan2019/m3icdManualSmall6FixW2v/current_best.pytorch --add_name _manual_small_6icd --weight_term 1 --top_k 2 --warm_start --near_cnn 0 > /local/datdb/ICD9multitask/multitask_model/m3icd6SmallFixW2vUpCnnMid6SgdFreeLabOff.txt



CUDA_VISIBLE_DEVICES=5 /home/datdb/anaconda3/bin/python3 -u /local/datdb/ICD9multitask/multitask_model/multitask.py --not_train_w2v_emb --not_update_cnn_att --epoch 200 --do_label_label --lr .0001 --lr_optim_y .01 --lr_predict_y .001 --epoch_predict_y 1000 --L2_scale 1 --result_folder m3icd6SmallFixW2vFixCnnMid6SgdCon --num_of_filter 50 --label_encoded_dim 50 --w2v_emb 100 --batch_size 16 --init_label_emb --label_layer_dim 6 --epoch_y 250 --epoch_params 20 --model_cnn /local/datdb/MIMIC3database/format10Jan2019/m3icdManualSmall6FixW2v/current_best.pytorch --model_load /local/datdb/MIMIC3database/format10Jan2019/m3icd6SmallFixW2vFixCnnMid6SgdCon/current_best.pytorch --add_name _manual_small_6icd --weight_term 1 --top_k 2 --warm_start --near_cnn 0 --do_constraint --lr_lagran 1 --start_last_best > /local/datdb/ICD9multitask/multitask_model/m3icd6SmallFixW2vFixCnnMid6SgdCon2.txt



CUDA_VISIBLE_DEVICES=2 /home/datdb/anaconda3/bin/python3 -u /local/datdb/ICD9multitask/multitask_model/multitask.py --not_train_w2v_emb --not_update_cnn_att --epoch 200 --do_label_label --lr .001 --lr_optim_y .01 --lr_predict_y .01 --epoch_predict_y 300 --L2_scale 1 --result_folder m3icd6SmallFixW2vFixCnnMid6NoWarmSgdFree --num_of_filter 50 --label_encoded_dim 50 --w2v_emb 100 --batch_size 16 --init_label_emb --label_layer_dim 6 --epoch_y 100 --epoch_params 5 --model_cnn /local/datdb/MIMIC3database/format10Jan2019/m3icdManualSmall6FixW2v/current_best.pytorch --model_load /local/datdb/MIMIC3database/format10Jan2019/m3icd6SmallFixW2vFixCnnMid6NoWarmSgdFree/current_best.pytorch --add_name _manual_small_6icd --weight_term 1 --top_k 2 --near_cnn 0 --start_last_best > /local/datdb/ICD9multitask/multitask_model/m3icd6SmallFixW2vFixCnnMid6NoWarmSgdFree.txt



CUDA_VISIBLE_DEVICES=4 /home/datdb/anaconda3/bin/python3 -u /local/datdb/ICD9multitask/multitask_model/multitask.py --not_train_w2v_emb --not_update_cnn_att --epoch 200 --do_label_label --lr .001 --lr_optim_y .01 --lr_predict_y .01 --epoch_predict_y 300 --L2_scale 1 --result_folder m3icd50FixW2vFixCnnMid25NoWarmSgdFree --num_of_filter 50 --label_encoded_dim 50 --w2v_emb 100 --batch_size 8 --init_label_emb --label_layer_dim 25 --epoch_y 100 --epoch_params 5 --model_cnn /local/datdb/MIMIC3database/format10Jan2019/m3icd50FixW2v/current_best.pytorch --model_load /local/datdb/MIMIC3database/format10Jan2019/m3icd50FixW2vFixCnnMid25NoWarmSgdFree/current_best.pytorch --add_name _50icd --weight_term 1 --top_k 5 --near_cnn 0 > /local/datdb/ICD9multitask/multitask_model/m3icd50FixW2vFixCnnMid25NoWarmSgdFree.txt


CUDA_VISIBLE_DEVICES=3 /home/datdb/anaconda3/bin/python3 -u /local/datdb/ICD9multitask/multitask_model/multitask.py --not_train_w2v_emb --not_update_cnn_att --epoch 200 --do_label_label --lr .001 --lr_optim_y .01 --lr_predict_y .01 --epoch_predict_y 300 --L2_scale 1 --result_folder m3icd50FixW2vFixCnnMid25NoWarmSgdCon --num_of_filter 50 --label_encoded_dim 50 --w2v_emb 100 --batch_size 8 --init_label_emb --label_layer_dim 25 --epoch_y 100 --epoch_params 5 --model_cnn /local/datdb/MIMIC3database/format10Jan2019/m3icd50FixW2v/current_best.pytorch --add_name _50icd --weight_term 1 --top_k 5 --near_cnn 0 --lr_lagran 1 --do_constraint > /local/datdb/ICD9multitask/multitask_model/m3icd50FixW2vFixCnnMid25NoWarmSgdCon.txt


CUDA_VISIBLE_DEVICES=2 /home/datdb/anaconda3/bin/python3 -u /local/datdb/ICD9multitask/multitask_model/multitask.py --not_train_w2v_emb --epoch 200 --do_label_label --lr .001 --lr_optim_y .1 --lr_predict_y .1 --epoch_predict_y 300 --L2_scale 1 --result_folder m3icd50FixW2vUpCnnMid25NoWarmSgdFree --num_of_filter 50 --label_encoded_dim 50 --w2v_emb 100 --batch_size 8 --init_label_emb --label_layer_dim 25 --epoch_y 100 --epoch_params 15 --model_cnn /local/datdb/MIMIC3database/format10Jan2019/m3icd50FixW2v/current_best.pytorch --add_name _50icd --weight_term 1 --top_k 5 --near_cnn 0 > /local/datdb/ICD9multitask/multitask_model/m3icd50FixW2vUpCnnMid25NoWarmSgdFree.txt


CUDA_VISIBLE_DEVICES=1 /home/datdb/anaconda3/bin/python3 -u /local/datdb/ICD9multitask/multitask_model/multitask.py --not_train_w2v_emb --epoch 200 --do_label_label --lr .001 --lr_optim_y .1 --lr_predict_y .1 --epoch_predict_y 300 --L2_scale 1 --result_folder m3icd50FixW2vUpCnnMid25WarmSgdFree --num_of_filter 50 --label_encoded_dim 50 --w2v_emb 100 --batch_size 8 --init_label_emb --label_layer_dim 25 --epoch_y 100 --epoch_params 15 --model_cnn /local/datdb/MIMIC3database/format10Jan2019/m3icd50FixW2v/current_best.pytorch --add_name _50icd --weight_term 1 --top_k 5 --near_cnn 0 --warm_start > /local/datdb/ICD9multitask/multitask_model/m3icd50FixW2vUpCnnMid25WarmSgdFree.txt


CUDA_VISIBLE_DEVICES=2 /home/datdb/anaconda3/bin/python3 -u /local/datdb/ICD9multitask/multitask_model/multitask.py --not_train_w2v_emb --epoch 1000 --do_label_label --lr .0001 --lr_optim_y .001 --lr_predict_y .001 --epoch_predict_y 1000 --L2_scale 1 --result_folder m3icd6SmallFixW2vUpCnnMid6NoWarmSgdFree --num_of_filter 50 --label_encoded_dim 50 --w2v_emb 100 --batch_size 16 --init_label_emb --label_layer_dim 6 --epoch_y 200 --epoch_params 25 --model_cnn /local/datdb/MIMIC3database/format10Jan2019/m3icdManualSmall6FixW2v/current_best.pytorch --model_load /local/datdb/MIMIC3database/format10Jan2019/m3icd6SmallFixW2vUpCnnMid6NoWarmSgdFree/current_best.pytorch --add_name _manual_small_6icd --weight_term 1 --top_k 2 --near_cnn 0 --start_last_best > /local/datdb/ICD9multitask/multitask_model/m3icd6SmallFixW2vUpCnnMid6NoWarmSgdFree.txt

CUDA_VISIBLE_DEVICES=1 /home/datdb/anaconda3/bin/python3 -u /local/datdb/ICD9multitask/multitask_model/multitask.py --not_train_w2v_emb --epoch 200 --do_label_label --lr .001 --lr_optim_y .1 --lr_predict_y .1 --epoch_predict_y 1000 --L2_scale 1 --result_folder m3icd50FixW2vUpCnnMid25WarmSgdFree --num_of_filter 50 --label_encoded_dim 50 --w2v_emb 100 --batch_size 8 --init_label_emb --label_layer_dim 25 --epoch_y 100 --epoch_params 25 --model_cnn /local/datdb/MIMIC3database/format10Jan2019/m3icd50FixW2v/current_best.pytorch --model_load /local/datdb/MIMIC3database/format10Jan2019/m3icd50FixW2vUpCnnMid25WarmSgdFree/current_best.pytorch --add_name _50icd --weight_term 1 --top_k 5 --near_cnn 0 --warm_start > /local/datdb/ICD9multitask/multitask_model/m3icd50FixW2vUpCnnMid25WarmSgdFree.txt


CUDA_VISIBLE_DEVICES=1 /home/datdb/anaconda3/bin/python3 -u /local/datdb/ICD9multitask/multitask_model/multitask.py --not_train_w2v_emb --epoch 500 --do_label_label --lr .0001 --lr_optim_y .01 --lr_predict_y .01 --epoch_predict_y 1000 --L2_scale 1 --result_folder m3icd6SmallFixW2vUpCnnMid6NoWarmSgdCon --num_of_filter 50 --label_encoded_dim 50 --w2v_emb 100 --batch_size 16 --init_label_emb --label_layer_dim 6 --epoch_y 100 --epoch_params 5 --model_cnn /local/datdb/MIMIC3database/format10Jan2019/m3icdManualSmall6FixW2v/current_best.pytorch --add_name _manual_small_6icd --weight_term 1 --top_k 2 --near_cnn 0 --brute_force --do_constraint --lr_lagran 1  > /local/datdb/ICD9multitask/multitask_model/m3icd6SmallFixW2vUpCnnMid6NoWarmSgdCon.txt


CUDA_VISIBLE_DEVICES=5 /home/datdb/anaconda3/bin/python3 -u /local/datdb/ICD9multitask/analysis/evaluate_manual_label.py --not_train_w2v_emb --not_update_cnn_att --epoch 200 --do_label_label --lr .0001 --lr_optim_y .01 --lr_predict_y .001 --epoch_predict_y 1000 --L2_scale 1 --result_folder m3icd6SmallFixW2vFixCnnMid6SgdCon --num_of_filter 50 --label_encoded_dim 50 --w2v_emb 100 --batch_size 16 --init_label_emb --label_layer_dim 6 --epoch_y 250 --epoch_params 20 --model_cnn /local/datdb/MIMIC3database/format10Jan2019/m3icdManualSmall6FixW2v/current_best.pytorch --model_load /local/datdb/MIMIC3database/format10Jan2019/m3icd6SmallFixW2vFixCnnMid6SgdCon/current_best.pytorch --add_name _manual_small_6icd --weight_term 1 --top_k 2 --warm_start --near_cnn 0 --do_constraint --lr_lagran 1 --start_last_best > /local/datdb/ICD9multitask/analysis/m3icd6SmallFixW2vFixCnnMid6SgdCon2filterCom.txt


CUDA_VISIBLE_DEVICES=1 /home/datdb/anaconda3/bin/python3 -u /local/datdb/ICD9multitask/multitask_model/multitask.py --not_train_w2v_emb --not_update_cnn_att --epoch 200 --do_label_label --lr .0001 --lr_optim_y .01 --lr_predict_y .01 --epoch_predict_y 500 --L2_scale 1 --result_folder m3icd6SmallFixW2vFixCnnPwSgdCon --num_of_filter 50 --label_encoded_dim 50 --w2v_emb 100 --batch_size 16 --init_label_emb --label_layer_dim 6 --epoch_y 500 --epoch_params 20 --model_cnn /local/datdb/MIMIC3database/format10Jan2019/m3icdManualSmall6FixW2v/current_best.pytorch --model_load /local/datdb/MIMIC3database/format10Jan2019/m3icd6SmallFixW2vFixCnnPwSgdCon/current_best.pytorch --add_name _manual_small_6icd --weight_term 1 --top_k 2 --warm_start --near_cnn 0 --do_constraint --lr_lagran 1 --start_last_best --pair_wise_only --brute_force > /local/datdb/ICD9multitask/multitask_model/m3icd6SmallFixW2vFixCnnPwSgdCon.txt


CUDA_VISIBLE_DEVICES=3 /home/datdb/anaconda3/bin/python3 -u /local/datdb/ICD9multitask/multitask_model/multitask.py --not_train_w2v_emb --not_update_cnn_att --epoch 200 --do_label_label --lr .0001 --lr_optim_y .01 --lr_predict_y .01 --epoch_predict_y 500 --L2_scale 1 --result_folder m3icd6SmallFixW2vFixCnnMid6SgdConRep --num_of_filter 50 --label_encoded_dim 50 --w2v_emb 100 --batch_size 16 --init_label_emb --label_layer_dim 6 --epoch_y 500 --epoch_params 20 --model_cnn /local/datdb/MIMIC3database/format10Jan2019/m3icdManualSmall6FixW2v/current_best.pytorch --model_load /local/datdb/MIMIC3database/format10Jan2019/m3icd6SmallFixW2vFixCnnMid6SgdCon/current_best.pytorch --add_name _manual_small_6icd --weight_term 1 --top_k 2 --warm_start --near_cnn 0 --do_constraint --lr_lagran 1 --start_last_best --brute_force --keep_feasible > /local/datdb/ICD9multitask/multitask_model/m3icd6SmallFixW2vFixCnnMid6SgdConRep.txt


CUDA_VISIBLE_DEVICES=4 /home/datdb/anaconda3/bin/python3 -u /local/datdb/ICD9multitask/multitask_model/multitask.py --not_train_w2v_emb --not_update_cnn_att --epoch 500 --do_label_label --lr .0001 --lr_optim_y .001 --lr_predict_y .001 --epoch_predict_y 1000 --L2_scale 1 --result_folder m3icd6SmallFixW2vFixCnnPwSgdFree --num_of_filter 50 --label_encoded_dim 50 --w2v_emb 100 --batch_size 16 --init_label_emb --label_layer_dim 6 --epoch_y 500 --epoch_params 20 --model_cnn /local/datdb/MIMIC3database/format10Jan2019/m3icdManualSmall6FixW2v/current_best.pytorch --model_load /local/datdb/MIMIC3database/format10Jan2019/m3icd6SmallFixW2vFixCnnPwSgdFree/current_best.pytorch --add_name _manual_small_6icd --weight_term 1 --top_k 2 --warm_start --near_cnn 0 --start_last_best --pair_wise_only --brute_force > /local/datdb/ICD9multitask/multitask_model/m3icd6SmallFixW2vFixCnnPwSgdFree.txt


CUDA_VISIBLE_DEVICES=2 /home/datdb/anaconda3/bin/python3 -u /local/datdb/ICD9multitask/multitask_model/multitask.py --not_train_w2v_emb --epoch 200 --do_label_label --lr .0001 --lr_optim_y .001 --lr_predict_y .001 --epoch_predict_y 1000 --L2_scale 1 --result_folder m3icd6SmallFixW2vUpCnnPwSgdFree --num_of_filter 50 --label_encoded_dim 50 --w2v_emb 100 --batch_size 16 --init_label_emb --label_layer_dim 6 --epoch_y 500 --epoch_params 20 --model_cnn /local/datdb/MIMIC3database/format10Jan2019/m3icdManualSmall6FixW2v/current_best.pytorch --model_load /local/datdb/MIMIC3database/format10Jan2019/m3icd6SmallFixW2vUpCnnPwSgdFree/current_best.pytorch --add_name _manual_small_6icd --weight_term 1 --top_k 2 --warm_start --near_cnn 0 --start_last_best --pair_wise_only --brute_force > /local/datdb/ICD9multitask/multitask_model/m3icd6SmallFixW2vUpCnnPwSgdFree2.txt


CUDA_VISIBLE_DEVICES=4 /home/datdb/anaconda3/bin/python3 -u /local/datdb/ICD9multitask/multitask_model/multitask.py --not_train_w2v_emb --not_update_cnn_att --epoch 200 --do_label_label --lr .0001 --lr_optim_y .01 --lr_predict_y .01 --epoch_predict_y 1000 --L2_scale 1 --result_folder m3icd50FixW2vFixCnnPwSgdFree --num_of_filter 50 --label_encoded_dim 50 --w2v_emb 100 --batch_size 8 --init_label_emb --label_layer_dim 25 --epoch_y 500 --epoch_params 20 --model_cnn /local/datdb/MIMIC3database/format10Jan2019/m3icd50FixW2v/current_best.pytorch --model_load /local/datdb/MIMIC3database/format10Jan2019/m3icd50FixW2vFixCnnPwSgdFree/current_best.pytorch --add_name _50icd --weight_term 1 --top_k 5 --warm_start --near_cnn 0 --start_last_best --pair_wise_only > /local/datdb/ICD9multitask/multitask_model/m3icd50FixW2vFixCnnPwSgdFree.txt

CUDA_VISIBLE_DEVICES=3 /home/datdb/anaconda3/bin/python3 -u /local/datdb/ICD9multitask/multitask_model/multitask.py --not_train_w2v_emb --epoch 200 --do_label_label --lr .0001 --lr_optim_y .001 --lr_predict_y .001 --epoch_predict_y 1000 --L2_scale 1 --result_folder m3icd50FixW2vUpCnnPwSgdFree --num_of_filter 50 --label_encoded_dim 50 --w2v_emb 100 --batch_size 8 --init_label_emb --label_layer_dim 25 --epoch_y 500 --epoch_params 20 --model_cnn /local/datdb/MIMIC3database/format10Jan2019/m3icd50FixW2v/current_best.pytorch --model_load /local/datdb/MIMIC3database/format10Jan2019/m3icd50FixW2vUpCnnPwSgdFree/current_best.pytorch --add_name _50icd --weight_term 1 --top_k 5 --warm_start --near_cnn 0 --start_last_best --pair_wise_only > /local/datdb/ICD9multitask/multitask_model/m3icd50FixW2vUpCnnPwSgdFree2.txt



cd /local/datdb/ICD9multitask/analysis/
CUDA_VISIBLE_DEVICES=1 /home/datdb/anaconda3/bin/python3 -u /local/datdb/ICD9multitask/analysis/evaluate_manual_label.py --not_train_w2v_emb --not_update_cnn_att --epoch 200 --do_label_label --lr .0001 --lr_optim_y .01 --lr_predict_y .01 --epoch_predict_y 500 --L2_scale 1 --result_folder m3icd6SmallFixW2vFixCnnPwSgdFree --num_of_filter 50 --label_encoded_dim 50 --w2v_emb 100 --batch_size 16 --init_label_emb --label_layer_dim 6 --epoch_y 500 --epoch_params 20 --model_cnn /local/datdb/MIMIC3database/format10Jan2019/m3icdManualSmall6FixW2v/current_best.pytorch --model_load /local/datdb/MIMIC3database/format10Jan2019/m3icd6SmallFixW2vFixCnnPwSgdFree/current_best.pytorch --add_name _manual_small_6icd --weight_term 1 --top_k 2 --warm_start --near_cnn 0 --do_constraint --lr_lagran 1 --start_last_best --pair_wise_only --brute_force --keep_feasible > m3icd6SmallFixW2vFixCnnPwSgdFree.txt

cd /local/datdb/ICD9multitask/analysis/
CUDA_VISIBLE_DEVICES=2 /home/datdb/anaconda3/bin/python3 -u /local/datdb/ICD9multitask/analysis/evaluate_manual_label.py --not_train_w2v_emb --not_update_cnn_att --epoch 200 --do_label_label --lr .001 --lr_optim_y .01 --lr_predict_y .01 --epoch_predict_y 300 --L2_scale 1 --result_folder m3icd6SmallFixW2vFixCnnMid6NoWarmSgdFree --num_of_filter 50 --label_encoded_dim 50 --w2v_emb 100 --batch_size 16 --init_label_emb --label_layer_dim 6 --epoch_y 100 --epoch_params 5 --model_cnn /local/datdb/MIMIC3database/format10Jan2019/m3icdManualSmall6FixW2v/current_best.pytorch --model_load /local/datdb/MIMIC3database/format10Jan2019/m3icd6SmallFixW2vFixCnnMid6NoWarmSgdFree/current_best.pytorch --add_name _manual_small_6icd --weight_term 1 --top_k 2 --near_cnn 0 --start_last_best > m3icd6SmallFixW2vFixCnnMid6NoWarmSgdFree.txt


4

